sudo: required

services:
  - docker

script:
  - docker build -t yt .
  - docker run -d --name yt yt
  - sleep 30
  - docker logs yt
  - docker exec yt /bin/sh -c "apk add --no-cache curl && curl -f localhost:5000"
